### ISSUE TITLE
Update naming of @emotion/core dependency

### ISSUE THREAD

**Issue by isellsoap** [infinum/emotion-normalize#13]
Since version 11 @emotion/core dependency has been renamed to @emotion/react (see [changelog](https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Freact%4011.0.0)).

**Comment by isellsoap** [comment]
See also PR https://github.com/infinum/emotion-normalize/pull/12

**Comment by heartistizio** [comment]
Hey! Any update on this? Would contribute, but there's already an open PR.

**Comment by isBatak** [comment]
Thx for PR, version 11.0.1 is released
